
const sharedData = { 


  groupz: {
    "Algemeen": "cijfers kleuren",
    "Mens & Gezondheid": "leven medisch",
    "Natuur & Milieu": "dieren planten weer stenen metalen",
    "Eten & Drinken": "eten snoep smaken",
    "Vrije Tijd & Lifestyle": "relaxen sport hobby muziek uitgaan kleren",
    "Reizen & Vervoer": "reizen verkeer auto space",
    "Huis & Wonen": "gereedschap ",
    "Taal & Communicatie": "taal geld",
    "Cultuur & Samenleving": "cultuur religie politiek religie officieel_instituut"
  },
  categories: {
            "cijfers": "1_tot_10 grote_cijfers wiskunde",
            "kleuren": "normaal",
            "leven": "mensen familie familieleden straat",
            "dieren": "fauna vogels vissen zee_creaturen insecten",
            "planten": "planten bomen groente fruit kruiden specerijen",
            "eten": "smaken keuken restaurant dinner ontbijt toetjes snoep",
            "sport": "surf voetbal zeilen boot zee_oceaan",
            "weer": "soorten klimaat",
            "relaxen": "thuis met_familie sauna therapie",
            "taal": "groet omgang voorzetsels werkwoorden",
            "cultuur": "informeel formeel vrienden straat",
            "kleren": "netjes gewoon opgedirkt schoenen",
            "uitgaan": "winkelen mall toko warung restaurant clubbing concert kroeg",
            "medisch": "personen gebouw symptomen klachten lichaamsdelen medicijnen",
            "reizen": "vliegveld ov station",
            "verkeer": "fiets autos voetganger vvmiddel route regels",
            "geld": "betaal_pin betaal_cash rekening crypto",
            "hobby": "speelgoed e-games board-games",
            "muziek": "luisteren instrumenten audio hifi",
            "visueel": "tv movies",
            "auto": "interieur onderdelen",
            "baan_werk": "baan",
            "gereedschap": "hout indoor outdoor heavy_equipment",
            "space": "planets stars zodiac",
            "metalen": "metalen",
            "stenen": "stenen edelstenen",
            "politiek": "officials",
            "officieel_instituut": "stadhuis politieburo kerk",
            "religie": "islam protestantism catholicism hinduism buddhism confucianism",
            "tec": "pc audio video"
        },

   wordLists: {
            "mensen": [
                ["ik", "saya"],
                ["jij", "kamu/lo"],
                ["hij", "dia"],
                ["zij (meisje)", "dia"],
                ["wij(zonder jou)", "kami"],
                ["wij(met jou)", "kita"],
                ["jullie", "kalian"],
                ["zij (groep)", "mereka"],
                ["vriend", "teman"],
                ["familie", "keluarga"],
                ["moeder", "ibu"],
                ["vader", "ayah"],
                ["U", "anda"]
            ],
            "familie": [
    ["opa", "kakek / opa"],
    ["oma", "nenek / oma"],
    ["vader", "ayah / bapak"],
    ["moeder", "ibu / mama"],
    ["broer", "kakak / adik laki-laki"],
    ["zus", "kakak / adik perempuan"],
    ["zoon", "anak laki-laki / putra"],
    ["dochter", "anak perempuan / putri"],
    ["oom", "paman / om"],
    ["kind", "anak"],
    ["tante", "bibi / tante"],
    ["neef", "sepupu laki-laki / keponakan laki-laki"],
    ["nicht", "sepupu perempuan / keponakan perempuan"]
],
"familieleden": [
    ["grootvader", "kakek / eyang kakung"],
    ["grootmoeder", "nenek / eyang putri"],
    ["kleinzoon", "cucu laki-laki"],
    ["kleindochter", "cucu perempuan"],
    ["schoonvader", "mertua laki-laki / ayah mertua"],
    ["schoonmoeder", "mertua perempuan / ibu mertua"],
    ["zwager", "ipar laki-laki / adik ipar laki-laki"],
    ["schoonzus", "ipar perempuan / adik ipar perempuan"],
    ["schoonbroer", "ipar laki-laki (suami kakak / kakak suami)"],
    ["schoonzus", "ipar perempuan (istri kakak / kakak istri)"],
    ["achteroom", "paman buyut / om buyut"],
    ["achternicht", "sepupu buyut / keponakan buyut perempuan"],
    ["neefje", "keponakan kecil laki-laki"],
    ["nichtje", "keponakan kecil perempuan"],
    ["schoonfamilie", "keluarga mertua / besan"],
    ["familie", "keluarga"],
    ["verwant", "kerabat / sanak saudara"]
],
            "groet": [
                ["hallo", "halo"],
                ["goeie morgen", "selamat pagi"],
                ["goeie middag", "selamat siang"],
                ["goeie avond", "selamat malam"],
                ["tot ziens", "sampai jumpa"],
                ["dank je", "terima kasih"],
                ["graag gedaan (bali)", "sama sama"],
                ["graag gedaan (java)", "gak apa apa"],
                ["hoe is het", "apa kabar"],
                ["relax", "santai aja"],
                ["gewoon", "biasa aja"],
                ["geen gedoe", "nggak usah"],
                ["hoe is het met jou", "apa kabarmu"]
            ],
            "omgang": [
                ["Hoe gaat het?", "Apa kabar?"],
                ["Lang niet gezien!", "Lama nggak ketemu!"],
                ["Wat doe jij tegenwoordig?", "Kamu lagi ngapain sekarang?"],
                ["Hoe is het met je familie?", "Gimana kabar keluargamu?"],
                ["Tot ziens!", "Sampai jumpa!"],
                ["Doe voorzichtig!", "Hati-hati ya!"],
                ["Succes ermee!", "Semangat ya!"],
                ["Leuk je te zien!", "Senang ketemu kamu!"],
                ["Tot snel!", "Sampai ketemu lagi!"],
                ["Pas op!", "Awas!"],
                ["Gefeliciteerd!", "Selamat ya!"],
                ["Sorry, mijn fout!", "Maaf, salahku!"]
            ],
            "straat": [
                ["Pas op voor de auto!", "Awas mobil!"],
                ["Kun je even opzij gaan?", "Bisa minggir sebentar?"],
                ["Waar is de halte?", "Halte-nya di mana?"],
                ["Mag ik erlangs?", "Boleh lewat?"],
                ["Kijk uit voor de fiets!", "Awas sepeda!"],
                ["Het is hier druk!", "Ramai banget di sini!"],
                ["Wacht even op groen!", "Tunggu lampu hijau dulu!"],
                ["Niet oversteken hier!", "Jangan nyebrang di sini!"],
                ["Linksaf", "Belok kiri"],
                ["rechtsaf", "belok kanan"],
                ["Rechtdoor", "Lurus aja"],
                ["Is dit de goede kant?", "Ini arah yang bener?"],
                ["Rustig aan!", "Pelan-pelan!"]
            ],
            "voorzetsels": [
    ["aan", "di / pada / ke"],
    ["achter", "di belakang"],
    ["af", "dari / turun"],
    ["behalve", "kecuali"],
    ["beneden", "di bawah"],
    ["bij", "di / pada / bersama"],
    ["binnen", "di dalam"],
    ["boven", "di atas"],
    ["buiten", "di luar"],
    ["door", "melalui / oleh"],
    ["in", "di / ke dalam"],
    ["langs", "di sepanjang / lewat"],
    ["met", "dengan"],
    ["na", "setelah"],
    ["naar", "ke / menuju"],
    ["naast", "di samping"],
    ["om", "sekitar / untuk"],
    ["onder", "di bawah"],
    ["op", "di atas / pada"],
    ["over", "tentang / di atas"],
    ["per", "per"],
    ["sinds", "sejak"],
    ["te", "di / ke"],
    ["tegen", "terhadap / melawan"],
    ["tot", "sampai"],
    ["uit", "dari / keluar"],
    ["van", "dari / milik"],
    ["voor", "untuk / di depan"],
    ["tussen", "di antara"],
    ["zonder", "tanpa"]
],
            "werkwoorden": [
    ["zijn", "ada / menjadi / berada"],
    ["hebben", "punya / memiliki"],
    ["doen", "melakukan"],
    ["gaan", "pergi"],
    ["komen", "datang"],
    ["willen", "ingin / mau"],
    ["kunnen", "bisa"],
    ["zeggen", "bilang / mengatakan"],
    ["maken", "membuat"],
    ["kijken", "melihat / menonton"],
    ["vragen", "bertanya"],
    ["weten", "tahu"],
    ["moeten", "harus"],
    ["werken", "bekerja"],
    ["eten", "makan"],
    ["drinken", "minum"],
    ["zien", "melihat"],
    ["vinden", "menemukan / merasa"],
    ["geven", "memberi"],
    ["nemen", "mengambil"],
    ["beginnen", "mulai"],
    ["eindigen", "selesai / berakhir"],
    ["spreken", "berbicara"],
    ["praten", "ngobrol / berbicara"],
    ["lezen", "membaca"],
    ["schrijven", "menulis"],
    ["helpen", "membantu"],
    ["leren", "belajar"],
    ["wonen", "tinggal"],
    ["slapen", "tidur"]
],
            "personen": [
                ["doktor", "dokter"],
                ["verpleegster", "perawat"],
                ["chirurg", "ahli bedah"],
                ["patient", "sabar"],
                ["tandarts", "dokter gigi"],
                ["fysio", "fisio"],
                ["apotheker", "apoteker"],
                ["masseur", "tukang pijat"],
                ["anesthesist", "ahli anestesi"]
            ],
            "fauna": [
                ["hond", "anjing"],
                ["kat", "kucing"],
                ["konijn", "kelinci"],
                ["paard", "kuda"],
                ["koe", "sapi"],
                ["varken", "babi"],
                ["schaap", "domba"],
                ["kip", "ayam"],
                ["olifant", "gajah"],
                ["tijger", "harimau"],
                ["aap", "monyet"],
                ["leeuw", "singa"]
            ],
            "vissen": [
                ["baars", "baars"],
                ["snoek", "gabus"],
                ["karper", "mas"],
                ["paling", "belut"],
                ["snoekbaars", "kakap putih"],
                ["voorn", "tawes"],
                ["brasem", "nilem"],
                ["melkvis", "bandeng"],
                ["meerval", "lele"],
                ["reuzengurami", "gurame"],
                ["tilapia", "ikan nila"],
                ["Indische makreel", "ikan kembung"]
            ],
            "vogels": [
                ["koolmees", "kutilang"],
                ["pimpelmees", "madu"],
                ["huismus", "gereja kecil"],
                ["roodborst", "robin"],
                ["ekster", "kacer"],
                ["houtduif", "dara"],
                ["merel", "kerewek"],
                ["mus", "gereja"],
                ["winterkoning", "troglodytes"],
                ["duif", "merpati"]
            ],
            "zee_creaturen": [
                ["zeehond", "anjing laut"],
                ["krab", "kepiting"],
                ["garnaal", "udang"],
                ["zeester", "bintang laut"],
                ["kwal", "ubur-ubur"],
                ["kokkel", "kerang kokkel"],
                ["mossel", "kerang hijau"],
                ["groene zeeschildpad", "penyu hijau"],
                ["karetschildpad", "penyu sisik"],
                ["doegong", "duyung"],
                ["reuzenmanta", "pari manta"],
                ["walvishaai", "hiu paus"]
            ],
            "insecten": [
                ["lieveheersbeestje", "kumbang koksi"],
                ["hommel", "lebah bumble"],
                ["bij", "lebah madu"],
                ["wesp", "tawon"],
                ["huisvlieg", "lalat rumah"],
                ["zweefvlieg", "lalat hover"],
                ["oorworm", "kutu telinga"],
                ["libelle", "capung"],
                ["kakkerlak", "kecoa"],
                ["mug", "nyamuk"],
                ["mier", "semut"],
                ["vlinder", "kupu-kupu"]
            ],
            "fruit": [
                ["appel", "apel"],
                ["banaan", "pisang"],
                ["sinaasappel", "jeruk"],
                ["aardbei", "stroberi"],
                ["peer", "pir"],
                ["druif", "anggur"],
                ["kers", "ceri"],
                ["ananas", "nanas"],
                ["mango", "mangga"],
                ["citroen", "jeruk lemon"],
                ["limoen", "Jeruk nipis"],
                ["meloen", "melon"]
             ],
             "kruiden": [
                ["basilicum", "kemangi"],
                ["koriander", "ketumbar"],
                ["munt", "mint"],
                ["dille", "adas"],
                ["tijm", "thyme"],
                ["rozemarijn", "rosemary"],
                ["salie", "sage"],
                ["dragon", "estragon"],
                ["bieslook", "kucai"],
                ["citroen gras", "serai"],
                ["oregano", "oregano"],
                ["laurier", "daun salam"]
             ],
             "groente": [
                ["wortel", "wortel"],
                ["ui", "bawang"],
                ["tomaat", "tomat"],
                ["sla", "selada"],
                ["komkommer", "timun"],
                ["aardappel", "kentang"],
                ["bloemkool", "kembang kol"],
                ["broccoli", "brokoli"],
                ["spinazie", "bayam"],
                ["knoflook", "bawang putih"],
                ["paprika", "paprika"],
                ["courgette", "zucchini"]
             ],
             "specerijen": [
                ["kaneel", "kayu manis"],
                ["kruidnagel", "cengkeh"],
                ["nootmuskaat", "pala"],
                ["gember", "jahe"],
                ["kurkuma", "kunyit"],
                ["komijn", "jinten"],
                ["kardemom", "kapulaga"],
                ["peper", "lada / merica"],
                ["anijs", "adas manis"],
                ["foelie", "bunga pala"],
                ["saffraan", "safron"],
                ["korianderzaad", "biji ketumbar"]
             ],
            "normaal": [
                ["rood", "merah"],
                ["zwart", "hitam"],
                ["blauw", "biru"],
                ["wit", "putih"],
                ["oranje", "oranye"],
                ["paars", "ungu"],
                ["roze", "merah muda"],
                ["groen", "hijau"],
                ["geel", "kuning"],
                ["bruin", "cokelat"],
                ["grijs", "abu-abu"]
            ],
            "exotic": [
                ["turquoise", "biru toska / turkuois"],
                ["lila", "ungu muda / lila"],
                ["magenta", "magenta"],
                ["indigo", "indigo"],
                ["paars", "ungu tua"],
                ["fuchsia", "fuchsia"],
                ["cyaan", "sian / cyan"],
                ["kobaltblauw", "biru kobalt"],
                ["saffier", "biru safir"],
                ["amethist", "ungu ametis"],
                ["smaragd", "hijau zamrud"],
                ["roze koraal", "merah muda karang"]
            ],
            "planten": [
                ["paardebloem", "bunga dandelion"],
                ["geranium", "kerenyam"],
                ["zonnebloem", "bunga matahari"],
                ["boterbloem", "bunga buttercup"],
                ["jasmijn", "melati"],
                ["hibiscus", "kembang sepatu"],
                ["frangipani/plumeria", "kamboja"],
                ["bougainville", "bougainvillea"],
                ["ixora", "soka"],
                ["roos", "mawar"],
                ["chrysant", "krisan"]
            ],
            "bomen": [
                ["boom", "ek"],
                ["eik", "ek"],
                ["beuk", "beech"],
                ["den", "pinus"],
                ["spar", "cemara"],
                ["berk", "birch"],
                ["esdoorn", "maple"],
                ["kastanje", "kastanye"],
                ["wilg", "willow"],
                ["linde", "linden"],
                ["populier", "poplar"],
                ["palm", "palem"]
            ],
            "gebouw": [
                ["ziekenhuis", "rumah sakit"],
                ["kliniek", "klinik"],
                ["dokterpraktijk", "praktik dokter"],
                ["apotheek", "apotik"],
                ["spoedeisende hulp", "instalasi gawat darurat / IGD"],
                ["polikliniek", "poliklinik"],
                ["laboratorium", "laboratorium"],
                ["röntgenafdeling", "ruang rontgen"],
                ["operatiekamer", "ruang operasi"],
                ["wachtkamer", "ruang tunggu"],
                ["kinderafdeling", "bangsal anak"],
                ["verloskamer", "ruang bersalin"]
            ],
            "symptomen": [
                ["koorts", "demam"],
                ["hoofdpijn", "sakit kepala"],
                ["hoesten", "batuk"],
                ["keelpijn", "sakit tenggorokan"],
                ["misselijk", "mual"],
                ["braken", "muntah"],
                ["diarree", "diare"],
                ["verstopping", "sembelit"],
                ["duizelig", "pusing"],
                ["kortademig", "sesak napas"],
                ["moe", "lelah / capek"],
                ["zweten", "berkeringat"]
            ],
            "klachten": [
                ["pijn", "sakit / nyeri"],
                ["jeuk", "gatal"],
                ["zwelling", "bengkak"],
                ["bloeding", "pendarahan"],
                ["uitslag", "ruam / ruam kulit"],
                ["stijf", "kaku"],
                ["zwak", "lemah"],
                ["hartkloppingen", "jantung berdebar"],
                ["brandend gevoel", "rasa terbakar"],
                ["druk op de borst", "tekanan di dada"],
                ["tintelingen", "kesemutan"],
                ["kramp", "kram"]
            ],
            "medicijnen": [
                ["paracetamol", "parasetamol"],
                ["ibuprofen", "ibuprofen"],
                ["amoxicilline", "amoksisilin"],
                ["pijnstiller", "penghilang rasa sakit"],
                ["antibiotica", "antibiotik"],
                ["hoestsiroop", "sirup batuk"],
                ["vitamine", "vitamin"],
                ["pleister", "plester"],
                ["zalf", "salep"],
                ["tabletten", "tablet"],
                ["injectie", "suntikan"],
                ["druppels", "tetes"]
            ],
            "lichaamsdelen": [
                ["hand", "tangan"],
                ["voet", "kaki"],
                ["arm", "lengan"],
                ["been", "kaki"],
                ["vinger", "jari"],
                ["teen", "kaki"],
                ["hoofd", "kepala"],
                ["hals", "leher"],
                ["ixora", "soka"],
                ["oor", "telinga"],
                ["mond", "mulut"],
                ["tong", "lidah"],
                ["pols", "pergelangan tangan"],
                ["schouder", "bahu"],
                ["enkel", "lajang"],
                ["knie", "lutut"]
            ],
            "vliegveld": [
                ["vliegveld", "bandara"],
                ["vliegtuig", "pesawat"],
                ["check-in", "check-in"],
                ["bagage", "bagasi"],
                ["rookruimte", "area merokok"],
                ["paspoort", "paspor"],
                ["gate", "gerbang"],
                ["vertrek", "keberangkatan"],
                ["aankomst", "kedatangan"],
                ["douane", "bea cukai"],
                ["veiligheidscontrole", "pemeriksaan keamanan"],
                ["boarding pass", "tiket masuk"],
                ["wachtruimte", "ruang tunggu"],
                ["stewardes", "pramugari"],
                ["steward", "pelayan"],
                ["belasting vrij", "bebas pajak"],
                ["bagageband", "konveyor bagasi"]
            ],
            "ov": [
                ["openbaar vervoer", "angkutan umum"],
                ["bus", "bus"],
                ["tram", "trem"],
                ["metro", "kereta bawah tanah / MRT"],
                ["halte", "halte"],
                ["kaartje", "tiket"],
                ["chauffeur", "sopir"],
                ["halteplaats", "pemberhentian"],
                ["lijn", "jalur"],
                ["retour", "pulang pergi"],
                ["abonnement", "langganan"],
                ["omwisselen", "tukar / transit"]
            ],
            "station": [
                ["station", "stasiun"],
                ["trein", "kereta api"],
                ["perron", "peron"],
                ["treinkaartje", "tiket kereta"],
                ["spoor", "rel"],
                ["loket", "loket"],
                ["vertrektijd", "waktu keberangkatan"],
                ["aankomsttijd", "waktu kedatangan"],
                ["spoorweg", "jalur kereta api"],
                ["bagagekluis", "loker bagasi"],
                ["informatiebalie", "meja informasi"],
                ["overstap", "transit / ganti kereta"]
            ],
            "smaken": [
                ["zoet", "manis"],
                ["zout", "asin"],
                ["zuur", "asam / masam"],
                ["bitter", "pahit"],
                ["pittig / scherp", "pedas"],
                ["pikant", "berbumbu"],
                ["kruidig", "beraroma rempah"],
                ["fris", "segar"],
                ["zacht", "lembut"],
                ["romig", "kental"],
                ["hartig", "gurih"],
                ["wrang", "sepat / kelat"]
            ],
            "keuken": [
                ["koken", "memasak"],
                ["recept", "resep"],
                ["pan", "panci"],
                ["koekenpan", "wajan"],
                ["oven", "oven"],
                ["snijden", "memotong"],
                ["roeren", "mengaduk"],
                ["bakken", "menggoreng / memanggang"],
                ["koken", "merebus"],
                ["kruiden", "bumbu"],
                ["zout", "garam"],
                ["peper", "merica"]
            ],
            "restaurant": [
                ["restaurant", "restoran"],
                ["menu", "menu"],
                ["ober", "pelayan / pramusaji"],
                ["bestellen", "memesan"],
                ["rekening", "bon / bill"],
                ["fooi", "tip"],
                ["tafel", "meja"],
                ["stoel", "kursi"],
                ["kaart", "daftar menu"],
                ["reserveren", "reservasi"],
                ["afhalen", "take away / bungkus"],
                ["serveren", "menyajikan"]
            ],
            "dinner": [
                ["diner", "makan malam"],
                ["hoofdgerecht", "hidangan utama"],
                ["bijgerecht", "hidangan pendamping"],
                ["soep", "sup"],
                ["salade", "salad"],
                ["rijst", "nasi"],
                ["vlees", "daging"],
                ["vis", "ikan"],
                ["groente", "sayur"],
                ["saus", "saus"],
                ["eten", "makan"],
                ["genieten", "menikmati"]
            ],
            "ontbijt": [
                ["ontbijt", "sarapan"],
                ["brood", "roti"],
                ["boter", "mentega"],
                ["kaas", "keju"],
                ["ei", "telur"],
                ["jam", "selai"],
                ["koffie", "kopi"],
                ["thee", "teh"],
                ["croissant", "kroisan"],
                ["yoghurt", "yogurt"],
                ["muesli", "muesli"],
                ["pannenkoek", "panekuk"]
            ],
            "toetjes": [
                ["toetje", "hidangan penutup / dessert"],
                ["ijs", "es krim"],
                ["pudding", "puding"],
                ["taart", "kue tart"],
                ["cake", "kue bolu"],
                ["chocolade", "cokelat"],
                ["fruit", "buah"],
                ["yoghurt", "yogurt"],
                ["flan", "flan / karamel"],
                ["crème brûlée", "krim brulee"],
                ["tiramisu", "tiramisu"],
                ["gebak", "kue kering"]
            ],
            "snoep": [
                ["snoep", "permen"],
                ["chocolade", "cokelat"],
                ["drop", "permen asam"],
                ["gom", "permen karet"],
                ["lolly", "permen lolipop"],
                ["marshmallow", "marshmallow"],
                ["gummybeer", "beruang karet"],
                ["zuurtje", "permen asam"],
                ["toffees", "permen karamel"],
                ["pepermunt", "permen mint"],
                ["kauwgom", "permen karet"],
                ["zuurtjes", "permen asam"]
            ],
                        "betaal_pin": [
                ["pinnen", "bayar pakai kartu"],
                ["pincode", "kode PIN"],
                ["pasje", "kartu ATM / kartu debit"],
                ["automaat", "ATM"],
                ["saldo", "saldo"],
                ["intoetsen", "memasuki"],
                ["opnemen", "tarik tunai"],
                ["chip", "chip"],
                ["contactloos", "tanpa kontak / tap"],
                ["limiet", "batas"],
                ["bevestigen", "konfirmasi"],
                ["betalen", "membayar"],
                ["prijs", "harga"],
                ["transactie", "transaksi"],
                ["kosten", "biaya"]
            ],
            "betaal_cash": [
                ["contant", "tunai"],
                ["geld", "uang"],
                ["briefje", "lembaran uang"],
                ["munten", "koin"],
                ["wisselgeld", "kembalian"],
                ["betalen", "bayar"],
                ["kassa", "kasir"],
                ["portemonnee", "dompet"],
                ["100 euro", "seratus euro"],
                ["fooi", "tip"],
                ["pinnen of cash?", "bayar kartu atau tunai?"],
                ["prijs", "harga"],
                ["korting", "diskon"],
                ["kleingeld", "uang kecil"]
            ],
            "rekening": [
                ["rekening", "rekening"],
                ["bankrekening", "rekening bank"],
                ["spaarrekening", "rekening tabungan"],
                ["betaalrekening", "rekening giro"],
                ["rente", "bunga"],
                ["saldo", "saldo"],
                ["overschrijving", "transfer"],
                ["incasso", "debit otomatis"],
                ["afschrift", "mutasi rekening"],
                ["IBAN", "nomor IBAN"],
                ["BIC", "kode BIC"],
                ["kosten", "biaya administrasi"]
            ],
            "crypto": [
                ["cryptocurrency", "mata uang kripto"],
                ["bitcoin", "bitcoin"],
                ["ethereum", "ethereum"],
                ["wallet", "dompet kripto"],
                ["exchange", "bursa kripto"],
                ["blockchain", "blockchain"],
                ["mining", "menambang"],
                ["koers", "harga / nilai tukar"],
                ["token", "token"],
                ["private key", "kunci pribadi"],
                ["seed phrase", "frasa pemulihan"],
                ["staking", "staking"]
            ],
            "fiets": [
                ["fiets", "sepeda"],
                ["fietsen", "bersepeda"],
                ["fietser", "pesepeda"],
                ["fietshelm", "helm sepeda"],
                ["fietsbel", "bel sepeda"],
                ["fietspad", "jalur sepeda"],
                ["band lek", "ban kempes"],
                ["pomp", "pompa"],
                ["slot", "kunci sepeda"],
                ["bagagedrager", "rak bagasi"],
                ["fietslamp", "lampu sepeda"],
                ["zadel", "sadel"]
            ],
            "autos": [
                ["auto", "mobil"],
                ["rijden", "mengemudi"],
                ["chauffeur", "sopir"],
                ["benzine", "bensin"],
                ["diesel", "solar"],
                ["parkeren", "parkir"],
                ["stuur", "setir"],
                ["rem", "rem"],
                ["gaspedaal", "gas"],
                ["koppeling", "kopling"],
                ["kofferbak", "bagasi"],
                ["raam", "kaca jendela"]
            ],
            "voetganger": [
                ["voetganger", "pejalan kaki"],
                ["lopen", "berjalan kaki"],
                ["zebrapad", "jalur penyeberangan"],
                ["stoep", "trotoar"],
                ["oversteekplaats", "tempat penyeberangan"],
                ["verkeerslicht", "lampu lalu lintas"],
                ["rood licht", "lampu merah"],
                ["groen licht", "lampu hijau"],
                ["oversteken", "menyeberang"],
                ["trottoir", "trotoar"],
                ["voetpad", "jalan kaki"],
                ["schouder", "bahu jalan"]
            ],
            "vvmiddel": [
                ["voertuig", "kendaraan"],
                ["bromfiets", "motor matic / sepeda motor"],
                ["motor", "motor"],
                ["auto", "mobil"],
                ["fiets", "sepeda"],
                ["step", "melangkah"],
                ["bus", "bis"],
                ["trein", "kereta"],
                ["vliegtuig", "pesawat terbang"],
                ["brommerkarretje", "bentor"],
                ["paardewagen", "andong/dokar"],
                ["minibusjes", "angkot"],
                ["taxi", "taksi"],
                ["scooter", "skuter"],
                ["vrachtwagen", "truk"],
                ["ambulance", "ambulans"],
                ["brandweerauto", "mobil pemadam kebakaran"],
                ["politieauto", "mobil polisi"]
            ],
            "route": [
                ["route", "rute"],
                ["weg", "jalan"],
                ["snelweg", "jalan tol"],
                ["afslag", "keluar / simpang susun"],
                ["richting", "arah"],
                ["rechtsaf", "belok kanan"],
                ["linksaf", "belok kiri"],
                ["rechtdoor", "lurus"],
                ["omleiding", "jalan memutar"],
                ["navigatie", "navigasi"],
                ["kaart", "peta"],
                ["gps", "gps"]
            ],
            "regels": [
                ["verkeersregels", "aturan lalu lintas"],
                ["snelheidslimiet", "batas kecepatan"],
                ["stoplicht", "lampu lalu lintas"],
                ["voorrang", "hak utama"],
                ["inhaalverbod", "larangan mendahului"],
                ["riem", "sabuk pengaman"],
                ["helm", "helm"],
                ["boete", "denda"],
                ["rijbewijs", "surat izin mengemudi / SIM"],
                ["parkeerverbod", "dilarang parkir"],
                ["fietspad verplicht", "wajib jalur sepeda"],
                ["rechts rijden", "berkendara di sebelah kanan"]
            ],
            "winkelen": [
                ["shoppen", "belanja"],
                ["kleren kopen", "beli baju"],
                ["uitverkoop", "diskon / obral"],
                ["winkelcentrum", "pusat perbelanjaan"],
                ["pashokje", "ruang ganti"],
                ["kassa", "kasir"],
                ["bonnetje", "struk / nota"],
                ["retour", "retur / pengembalian"],
                ["grootte", "ukuran"],
                ["korting", "diskon"],
                ["winkelwagen", "keranjang belanja"],
                ["betalen", "bayar"]
            ],
            "mall": [
                ["winkelcentrum", "mal / pusat perbelanjaan"],
                ["bioscoop", "bioskop"],
                ["foodcourt", "food court"],
                ["lift", "lift / eskalator"],
                ["parkeren", "parkir"],
                ["toilet", "toilet / kamar kecil"],
                ["atrium", "atrium"],
                ["fontein", "air mancur"],
                ["speelplaats", "tempat bermain anak"],
                ["bioscoopticket", "tiket bioskop"],
                ["promotie", "promo"],
                ["klantenservice", "layanan pelanggan"]
            ],
            "toko": [
                ["winkel", "toko"],
                ["kruidenier", "toko kelontong"],
                ["markt", "pasar"],
                ["supermarkt", "supermarket"],
                ["minimarkt", "minimarket"],
                ["kassa", "kasir"],
                ["prijs", "harga"],
                ["rekening", "nota / struk"],
                ["plastic zak", "kantong plastik"],
                ["vers", "segar"],
                ["pakket", "paket"],
                ["afrekenen", "bayar di kasir"]
            ],
            "warung": [
                ["eetstalletje", "warung makan"],
                ["koffie", "kopi"],
                ["thee", "teh"],
                ["nasi goreng", "nasi goreng"],
                ["mie goreng", "mie goreng"],
                ["saté", "sate"],
                ["soep", "soto / sup"],
                ["ijs", "es"],
                ["sigaret", "rokok"],
                ["plastic stoel", "kursi plastik"],
                ["take away", "bungkus / bawa pulang"],
                ["rekening", "hitung"]
            ],
            "restaurant": [
                ["restaurant", "restoran"],
                ["menu", "menu"],
                ["ober", "pelayan / pramusaji"],
                ["bestellen", "pesan"],
                ["rekening", "bill / bon"],
                ["fooi", "tip"],
                ["voorgerecht", "hidangan pembuka"],
                ["hoofdgerecht", "hidangan utama"],
                ["nagerecht", "hidangan penutup / dessert"],
                ["drinken", "minuman"],
                ["reserveren", "reservasi"],
                ["tafel", "meja"]
            ],
            "clubbing": [
                ["discotheek", "diskotik / klub malam"],
                ["dansvloer", "lantai dansa"],
                ["dj", "disk jockey / dj"],
                ["muziek", "musik"],
                ["drankje", "minuman"],
                ["feest", "pesta"],
                ["bouncer", "penjaga pintu"],
                ["cover charge", "uang masuk"],
                ["lightshow", "pertunjukan lampu"],
                ["afterparty", "after party"],
                ["crowd", "kerumunan"],
                ["chill", "santai"]
            ],
            "concert": [
                ["concert", "konser"],
                ["kaartje", "tiket"],
                ["podium", "panggung"],
                ["band", "band"],
                ["zanger", "penyanyi"],
                ["gitaar", "gitar"],
                ["drum", "drum"],
                ["publiek", "penonton"],
                ["applaus", "tepuk tangan"],
                ["encore", "encore"],
                ["festival", "festival"],
                ["geluid", "suara"]
            ],
            "kroeg": [
                ["kroeg", "bar / kedai"],
                ["biertje", "bir"],
                ["pils", "bir pilsner"],
                ["jenever", "jenever"],
                ["borrel", "minum-minum"],
                ["barkeeper", "bartender"],
                ["kruk", "bangku bar"],
                ["hapje", "camilan"],
                ["biljart", "biliar"],
                ["darts", "panah"],
                ["muziekje", "musik kecil"],
                ["laat", "malam"]
            ],
            "luisteren": [
                ["luisteren", "mendengarkan"],
                ["muziek luisteren", "dengar musik"],
                ["playlist", "daftar putar"],
                ["koptelefoon", "headphone"],
                ["oortjes", "earphone"],
                ["volume", "volume"],
                ["nummer", "lagu"],
                ["album", "album"],
                ["artiest", "artis"],
                ["streaming", "streaming"],
                ["downloaden", "unduh"],
                ["afspelen", "putar"]
            ],
            "instrumenten": [
                ["gitaar", "gitar"],
                ["piano", "piano"],
                ["drum", "drum"],
                ["viool", "biola"],
                ["basgitaar", "bas gitar"],
                ["fluit", "seruling"],
                ["trompet", "terompet"],
                ["saxfoon", "saksofon"],
                ["keyboard", "keyboard"],
                ["ukulele", "ukulele"],
                ["harmonica", "harmonika"],
                ["cello", "cello"]
            ],
            "audio": [
                ["geluid", "suara"],
                ["luidspreker", "speaker"],
                ["microfoon", "mikrofon"],
                ["geluidskwaliteit", "kualitas suara"],
                ["stereo", "stereo"],
                ["surround", "surround"],
                ["mp3", "mp3"],
                ["wav", "wav"],
                ["bitrate", "bitrate"],
                ["versterker", "amplifier"],
                ["recorder", "perekam"],
                ["podcast", "podcast"]
            ],
            "hifi": [
                ["hifi", "hifi"],
                ["versterker", "amplifier"],
                ["luidspreker", "speaker hi-fi"],
                ["platenspeler", "pemutar piringan hitam"],
                ["cd-speler", "pemutar CD"],
                ["dac", "dac"],
                ["analoog", "analog"],
                ["digitaal", "digital"],
                ["vinyl", "vinyl"],
                ["tube", "tabung vakum"],
                ["tuner", "tuner"],
                ["receiver", "receiver"]
            ],
            "informeel": [
                ["yo", "yo / bro"],
                ["hé", "hé / hey"],
                ["gaaf", "keren / mantap"],
                ["chill", "santai / chill"],
                ["lekker", "enak / asik"],
                ["vet", "keren banget"],
                ["niks aan de hand", "nggak apa-apa"],
                ["doei", "dadah / bye"],
                ["tot zo", "bentaran lagi"],
                ["later", "nanti"],
                ["oké", "oke / sip"],
                ["tuurlijk", "tentu / ya dong"]
            ],
            "formeel": [
                ["goedemorgen", "selamat pagi"],
                ["goedemiddag", "selamat siang"],
                ["goedenavond", "selamat malam"],
                ["dank u wel", "terima kasih banyak"],
                ["alstublieft", "silakan"],
                ["excuseer mij", "permisi / maaf"],
                ["met wie spreek ik?", "dengan siapa saya berbicara?"],
                ["u spreekt met", "ini berbicara dengan"],
                ["tot ziens", "sampai jumpa"],
                ["prettige dag", "selamat hari"],
                ["graag gedaan", "sama-sama"],
                ["mag ik u iets vragen?", "boleh saya bertanya?"]
            ],
            "vrienden": [
                ["vriend", "teman"],
                ["beste vriend", "sahabat"],
                ["kameraad", "kawan"],
                ["maatje", "teman akrab"],
                ["buddy", "sobat"],
                ["hangen", "nongkrong"],
                ["chillen", "santai bareng"],
                ["feestje", "pesta kecil"],
                ["uitgaan", "jalan-jalan / clubbing"],
                ["appje", "chat / pesan"],
                ["belletje", "telpon sebentar"],
                ["afspreken", "janjian"]
            ],
            "straat": [
                ["straat", "jalan"],
                ["stoep", "trotoar"],
                ["zebrapad", "jalur zebra"],
                ["verkeerslicht", "lampu lalu lintas"],
                ["auto", "mobil"],
                ["fiets", "sepeda"],
                ["voetganger", "pejalan kaki"],
                ["bord", "rambu"],
                ["lantaarnpaal", "tiang lampu jalan"],
                ["vuilnisbak", "tempat sampah"],
                ["straatnaambord", "papan nama jalan"],
                ["oversteekplaats", "tempat penyeberangan"]
            ],
            "speelgoed": [
                ["pop", "boneka"],
                ["beer", "beruang teddy / boneka beruang"],
                ["auto", "mobil-mobilan"],
                ["bal", "bola"],
                ["lego", "lego"],
                ["puzzel", "puzzle / teka-teki"],
                ["blok", "balok mainan"],
                ["trein", "kereta api mainan"],
                ["vliegtuig", "pesawat terbang mainan"],
                ["knuffel", "boneka peluk"],
                ["poppenhuis", "rumah boneka"],
                ["kleurboek", "buku mewarnai"]
            ],
            "e-games": [
                ["spel", "permainan"],
                ["videogame", "permainan video"],
                ["computer", "komputer"],
                ["telefoon", "ponsel / handphone"],
                ["controller", "pengontrol / stik game"],
                ["level", "level"],
                ["punten", "poin / skor"],
                ["multiplayer", "multiplayer"],
                ["online", "online"],
                ["karakter", "karakter"],
                ["win", "menang"],
                ["verlies", "kalah"]
            ],
            "board-games": [
                ["bordspel", "permainan papan"],
                ["schaken", "catur"],
                ["dammen", "dam"],
                ["monopoly", "monopoli"],
                ["mens erger je niet", "ular tangga"],
                ["kaarten", "kartu"],
                ["dobbelsteen", "dadu"],
                ["strategie", "strategi"],
                ["beurt", "giliran"],
                ["winnaar", "pemenang"],
                ["speler", "pemain"],
                ["bord", "papan"]
            ],
            "sauna": [
                ["sauna", "sauna"],
                ["stoomcabine", "ruang uap"],
                ["hitte", "panas"],
                ["relaxen", "bersantai"],
                ["zweten", "berkeringat"],
                ["handdoek", "handuk"],
                ["koud bad", "bak mandi dingin"],
                ["stoombad", "ruang uap panas"],
                ["saunagang", "sesi sauna"],
                ["rustruimte", "ruang istirahat"],
                ["infuus", "infus / minum air banyak"],
                ["saunamuts", "topi sauna"]
            ],
            "therapie": [
                ["therapie", "terapi"],
                ["massage", "pijet / pijat"],
                ["aromatherapie", "aromaterapi"],
                ["yoga", "yoga"],
                ["meditatie", "meditasi"],
                ["reflexologie", "refleksologi"],
                ["acupunctuur", "akupunktur"],
                ["reiki", "reiki"],
                ["ontspanning", "relaksasi"],
                ["stress", "stres"],
                ["ademhaling", "pernapasan"],
                ["mindfulness", "kesadaran penuh"]
            ],
            "thuis": [
                ["thuis", "di rumah"],
                ["relaxen", "bersantai"],
                ["bank", "sofa"],
                ["thee", "teh"],
                ["boek", "buku"],
                ["muziek", "musik"],
                ["kaars", "lilin"],
                ["bad", "mandi"],
                ["film kijken", "nonton film"],
                ["slapen", "tidur"],
                ["rustig", "tenang"],
                ["comfortabel", "nyaman"]
            ],
            "met_familie": [
                ["familie", "keluarga"],
                ["samen", "bersama"],
                ["spelletje", "main permainan"],
                ["filmavond", "malam nonton film"],
                ["eten", "makan bersama"],
                ["praten", "ngobrol"],
                ["knuffelen", "pelukan"],
                ["uitstapje", "jalan-jalan bersama"],
                ["herinnering", "kenangan"],
                ["lachen", "tertawa"],
                ["rustig", "tenang bersama"],
                ["thuis", "di rumah bersama"]
            ],
            "interieur": [
                ["dashboard", "dasbor"],
                ["stuurwiel", "setir"],
                ["stoel", "kursi"],
                ["bank", "bangku belakang"],
                ["veiligheidsgordel", "sabuk pengaman"],
                ["airbag", "kantong udara"],
                ["handschoenenvak", "laci dasbor"],
                ["pook", "tuas persneling"],
                ["pedalen", "pedal"],
                ["raam", "kaca jendela"],
                ["spiegel", "kaca spion"],
                ["zonneklep", "kaca matahari"]
            ],
            "onderdelen": [
                ["motor", "mesin"],
                ["accu", "aki"],
                ["rem", "rem"],
                ["band", "ban"],
                ["velg", "velg"],
                ["uitlaat", "knalpot"],
                ["radiator", "radiator"],
                ["olie", "oli"],
                ["filter", "filter"],
                ["bougie", "busi"],
                ["distributieriem", "sabuk timing"],
                ["schokdemper", "peredam kejut"]
            ],
            "metalen": [
                ["ijzer", "besi"],
                ["staal", "baja"],
                ["aluminium", "alumunium"],
                ["koper", "tembaga"],
                ["lood", "timbal"],
                ["zink", "seng"],
                ["tin", "timah"],
                ["nikkel", "nikel"],
                ["chroom", "krom"],
                ["magnesium", "magnesium"],
                ["titanium", "titanium"],
                ["goud", "emas"],
                ["zilver", "perak"],
                ["brons", "perunggu"],
                ["puur goud", "emas murni"]
            ],
            "surf": [
                ["surfen", "berselancar"],
                ["surfplank", "papan selancar"],
                ["golven", "ombak"],
                ["big wave", "ombak besar"],
                ["shortboard", "papan pendek"],
                ["longboard", "papan panjang"],
                ["leash", "tali pengaman"],
                ["wax", "lilin papan"],
                ["surfspot", "tempat selancar"],
                ["drop in", "masuk ombak"],
                ["wipeout", "jatuh dari ombak"],
                ["spot", "tempat"],
                ["board", "papan"],
                ["golf", "ombak"],
                ["zee", "laut"],
                ["strand", "pantai"],
                ["barrel", "tabung ombak"],
                ["dude", "bung"]
            ],
            "voetbal": [
                ["voetbal", "sepak bola"],
                ["gras", "rumput"],
                ["wedstrijd", "pertandingan"],
                ["doel", "gawang"],
                ["speler", "pemain"],
                ["doelman", "kiper"],
                ["scheidsrechter", "wasit"],
                ["goal", "gol"],
                ["penalty", "penalti"],
                ["vrije trap", "tendangan bebas"],
                ["corner", "tendangan sudut"],
                ["kaart", "kartu"],
                ["fluiten", "peluit"]
            ],
            "netjes": [
                ["pak", "jas dan celana"],
                ["stropdas", "dasi"],
                ["overhemd", "kemeja"],
                ["blazer", "blazer"],
                ["rok", "rok"],
                ["jurk", "gaun"],
                ["pumps", "sepatu hak tinggi"],
                ["kostuum", "setelan jas"],
                ["vest", "rompi / rompi"],
                ["das", "dasi"],
                ["manchetknopen", "kancing manset"],
                ["riem", "sabuk"]
            ],
            "gewoon": [
                ["spijkerbroek", "celana jeans"],
                ["T-shirt", "kaos"],
                ["trui", "sweater"],
                ["hoodie", "hoodie"],
                ["sneaker", "sepatu kets"],
                ["short", "celana pendek"],
                ["shirt", "kemeja kasual"],
                ["jurk", "dress kasual"],
                ["legging", "legging"],
                ["joggingbroek", "celana olahraga"],
                ["top", "atasan"],
                ["vest", "jaket tipis"]
            ],
            "opgedirkt": [
                ["high heels", "sepatu hak tinggi"],
                ["cocktailjurk", "gaun koktail"],
                ["smoking", "smoking"],
                ["stropdas", "dasi"],
                ["make-up", "make-up"],
                ["juwelen", "perhiasan"],
                ["kleding", "pakaian mewah"],
                ["avondkleding", "pakaian malam"],
                ["glitter", "glitter"],
                ["kralen", "manik-manik"],
                ["stiletto", "stiletto"],
                ["clutch", "tas kecil"]
            ],
            "schoenen": [
                ["schoenen", "sepatu"],
                ["sneaker", "kets"],
                ["laarzen", "bot"],
                ["sandalen", "sandal"],
                ["hakken", "hak"],
                ["klompen", "klompen"],
                ["slippers", "sandal jepit"],
                ["pumps", "sepatu hak tinggi"],
                ["sportschoenen", "sepatu olahraga"],
                ["loafers", "loafers"],
                ["sneakers", "kets"],
                ["schoenendoos", "kotak sepatu"]
            ],
            "1_tot_10": [
                ["één", "satu"],
                ["twee", "dua"],
                ["drie", "tiga"],
                ["vier", "empat"],
                ["vijf", "lima"],
                ["zes", "enam"],
                ["zeven", "tujuh"],
                ["acht", "delapan"],
                ["negen", "sembilan"],
                ["tien", "sepuluh"],
                ["nul", "nol"],
                ["plus", "tambah"]
            ],
            "grote_cijfers": [
                ["honderd", "seratus"],
                ["duizend", "seribu"],
                ["tienduizend", "sepuluh ribu"],
                ["honderdduizend", "seratus ribu"],
                ["miljoen", "juta"],
                ["tien miljoen", "sepuluh juta"],
                ["honderd miljoen", "seratus juta"],
                ["miljard", "miliar"],
                ["biljoen", "triliun"],
                ["eerste", "pertama"],
                ["tweede", "kedua"],
                ["derde", "ketiga"]
            ],
            "wiskunde": [
                ["plus", "tambah"],
                ["min", "kurang"],
                ["keer", "kali"],
                ["delen", "bagi"],
                ["gelijk", "sama dengan"],
                ["som", "jumlah"],
                ["verschil", "selisih"],
                ["product", "hasil kali"],
                ["quotiënt", "hasil bagi"],
                ["breuk", "pecahan"],
                ["procent", "persen"],
                ["vierkant", "kuadrat"]
            ],
            "tv": [
                ["televisie", "televisi"],
                ["tv", "TV"],
                ["programma", "programa"],
                ["zender", "saluran"],
                ["afstandsbediening", "remote control"],
                ["kanaal", "saluran TV"],
                ["series", "seri"],
                ["nieuws", "berita"],
                ["film", "film"],
                ["realityshow", "acara realitas"],
                ["reclame", "iklan"],
                ["smart TV", "TV pintar"]
            ],
            "movies": [
                ["film", "film"],
                ["bioscoop", "bioskop"],
                ["actiefilm", "film aksi"],
                ["komedie", "komedi"],
                ["drama", "drama"],
                ["horror", "horor"],
                ["thriller", "thriller"],
                ["animatie", "animasi"],
                ["documentaire", "dokumenter"],
                ["trailer", "cuplikan"],
                ["acteur", "aktor"],
                ["regisseur", "sutradara"]
            ],
            "soorten": [
                ["weer", "cuaca"],
                ["zonnig", "cerah"],
                ["bewolkt", "berawan"],
                ["regen", "hujan"],
                ["onweer", "petir / guntur"],
                ["mist", "kabut"],
                ["wind", "angin"],
                ["sneeuw", "salju"],
                ["hagel", "hujan es"],
                ["storm", "badai"],
                ["warm", "panas"],
                ["koud", "dingin"]
            ],
            "klimaat": [
                ["klimaat", "iklim"],
                ["tropisch", "tropis"],
                ["mediterraan", "mediterania"],
                ["continentaal", "kontinental"],
                ["polair", "polar"],
                ["woestijn", "gurun"],
                ["regenwoud", "hutan hujan tropis"],
                ["gemiddelde temperatuur", "suhu rata-rata"],
                ["neerslag", "curah hujan"],
                ["seizoen", "musim"],
                ["droog", "kering"],
                ["vochtig", "lembab"]
            ],
            "baan": [
                ["baan", "pekerjaan"],
                ["werk", "kerja"],
                ["sollicitatie", "lamaran kerja"],
                ["cv", "CV / daftar riwayat hidup"],
                ["salaris", "gaji"],
                ["contract", "kontrak"],
                ["vakantie", "cuti"],
                ["overwerk", "lembur"],
                ["collega", "rekan kerja"],
                ["baas", "bos"],
                ["ontslag", "pemecatan"],
                ["pensioen", "pensiun"]
            ],
            "hout": [
                ["hout", "kayu"],
                ["zaag", "gergaji"],
                ["hamer", "palu"],
                ["spijker", "paku"],
                ["schroef", "sekrup"],
                ["boor", "bor"],
                ["schuurpapier", "amplastik"],
                ["lijm", "lem"],
                ["verf", "cat"],
                ["beitel", "pahat"],
                ["meetlint", "meteran"],
                ["werkbank", "meja kerja"]
            ],
            "indoor": [
                ["schroevendraaier", "obeng"],
                ["tang", "tang"],
                ["moersleutel", "kunci pas"],
                ["inbussleutel", "kunci L / kunci inbus"],
                ["plug", "stekker / colokan"],
                ["lamp", "lampu"],
                ["stopcontact", "stopkontak"],
                ["verfroller", "kuas rol"],
                ["kwast", "kuas"],
                ["meetlint", "meteran"],
                ["waterpas", "waterpas"],
                ["stofzuiger", "penyedot debu"]
            ],
            "outdoor": [
                ["grasmaaier", "mesin potong rumput"],
                ["hark", "penggaruk"],
                ["schep", "sekop"],
                ["tuinslang", "selang taman"],
                ["zaag", "gergaji"],
                ["hamer", "palu"],
                ["spade", "cangkul"],
                ["kruiwagen", "gerobak dorong"],
                ["snoeischaar", "gunting tanaman"],
                ["tuinborstel", "sapu taman"],
                ["tuinbank", "bangku taman"],
                ["schop", "sekop kecil"]
            ],
            "heavy_equipment": [
                ["graafmachine", "ekskavator"],
                ["bulldozer", "buldoser"],
                ["kraan", "kran"],
                ["tractor", "traktor"],
                ["vrachtwagen", "truk"],
                ["roller", "pemadat"],
                ["dumptruck", "truk sampah"],
                ["shovel", "shovel"],
                ["betonmixer", "molenteng semen"],
                ["hoogwerker", "alat angkat tinggi"],
                ["asfaltmachine", "alat pengaspal"],
                ["heftruck", "forklift"]
            ],
            "planets": [
                ["planeet", "planet"],
                ["zon", "matahari"],
                ["maan", "bulan"],
                ["Mercurius", "Merkurius"],
                ["Venus", "Venus"],
                ["Aarde", "Bumi"],
                ["Mars", "Mars"],
                ["Jupiter", "Yupiter"],
                ["Saturnus", "Saturnus"],
                ["Uranus", "Uranus"],
                ["Neptunus", "Neptunus"],
                ["Pluto", "Pluto"]
            ],
            "stars": [
                ["ster", "bintang"],
                ["sterrenbeeld", "zodiak / rasi bintang"],
                ["Melkweg", "Bima Sakti"],
                ["helder", "terang"],
                ["vallende ster", "bintang jatuh"],
                ["nova", "nova"],
                ["supernova", "supernova"],
                ["zwarte gat", "lubang hitam"],
                ["constellatie", "konstelasi"],
                ["poolster", "bintang utara"],
                ["Sirius", "Sirius"],
                ["Orion", "Orion"]
            ],
            "zodiac": [
                ["Ram", "Aries"],
                ["Stier", "Taurus"],
                ["Tweelingen", "Gemini"],
                ["Kreeft", "Cancer"],
                ["Leeuw", "Leo"],
                ["Maagd", "Virgo"],
                ["Weegschaal", "Libra"],
                ["Schorpioen", "Scorpio"],
                ["Boogschutter", "Sagittarius"],
                ["Steenbok", "Capricorn"],
                ["Waterman", "Aquarius"],
                ["Vissen", "Pisces"]
            ],
            "officials": [
                ["president", "presiden"],
                ["minister", "menteri"],
                ["parlement", "parlemen"],
                ["premier", "perdana menteri"],
                ["burgemeester", "walikota"],
                ["gouverneur", "gubernur"],
                ["ambtenaar", "pegawai negeri"],
                ["diplomaat", "diplomat"],
                ["rechter", "hakim"],
                ["politiechef", "kepala polisi"],
                ["senator", "senator"],
                ["parlementslid", "anggota parlemen"]
            ],
            "stadhuis": [
                ["stadhuis", "balai kota"],
                ["gemeente", "pemerintah kota"],
                ["burgemeester", "walikota"],
                ["raadszaal", "ruang sidang dewan"],
                ["burgerzaken", "kantor kependudukan"],
                ["trouwzaal", "ruang pernikahan sipil"],
                ["vergunning", "izin"],
                ["belasting", "pajak daerah"],
                ["paspoort", "paspor"],
                ["identiteitskaart", "KTP"],
                ["archief", "arsip"],
                ["loket", "loket pelayanan"]
            ],
            "politieburo": [
                ["politiebureau", "kantor polisi"],
                ["politieagent", "polisi"],
                ["commissaris", "komisaris"],
                ["aangifte", "laporan polisi"],
                ["verhoor", "pemeriksaan"],
                ["handboeien", "borgol"],
                ["patrouille", "patroli"],
                ["arrestatie", "penangkapan"],
                ["proces-verbaal", "berita acara"],
                ["getuige", "saksi"],
                ["verdachte", "tersangka"],
                ["slachtoffer", "korban"]
            ],
            "kerk": [
                ["kerk", "gereja"],
                ["priester", "pendeta / pastor"],
                ["mis", "misa"],
                ["preek", "khotbah"],
                ["altaar", "altar"],
                ["kruis", "salib"],
                ["bijbel", "Alkitab"],
                ["doop", "pembaptisan"],
                ["huwelijk", "pernikahan gereja"],
                ["begrafenis", "pemakaman gereja"],
                ["koor", "paduan suara"],
                ["klok", "lonceng gereja"]
            ],
            "islam": [
                ["moskee", "masjid"],
                ["gebed", "shalat"],
                ["ramadan", "ramadhan"],
                ["vasten", "puasa"],
                ["koran", "Al-Qur'an"],
                ["profeet", "nabi"],
                ["mecca", "Mekkah"],
                ["hadj", "haji"],
                ["imam", "imam"],
                ["azaan", "azan / adzan"],
                ["vrijdaggebed", "shalat Jumat"],
                ["zakat", "zakat"]
            ],
            "protestantism": [
                ["protestants", "Protestan"],
                ["kerk", "gereja"],
                ["predikant", "pendeta"],
                ["bijbel", "Alkitab"],
                ["preek", "khotbah"],
                ["dopen", "pembaptisan"],
                ["avondmaal", "perjamuan kudus"],
                ["psalm", "mazmur"],
                ["zondagsschool", "sekolah minggu"],
                ["hervorming", "reformasi"],
                ["calvinisme", "kalvinisme"],
                ["lutheranisme", "lutheranisme"]
            ],
            "catholicism": [
                ["katholiek", "Katolik"],
                ["paus", "paus"],
                ["mis", "misa"],
                ["priester", "pastor"],
                ["biecht", "pengakuan dosa"],
                ["communie", "perjamuan kudus"],
                ["doop", "pembaptisan"],
                ["heilige", "santo / santa"],
                ["kruis", "salib"],
                ["rozenkrans", "rosario"],
                ["klooster", "biara"],
                ["kathedraal", "katedral"]
            ],
            "hinduism": [
                ["hindoe", "Hindu"],
                ["dharma", "dharma"],
                ["karma", "karma"],
                ["reïncarnatie", "kelahiran kembali"],
                ["tempel", "pura"],
                ["god", "dewa"],
                ["goddess", "dewi"],
                ["ganesha", "Ganesha"],
                ["shiva", "Siwa"],
                ["vishnu", "Wisnu"],
                ["brahma", "Brahma"],
                ["puja", "puja"]
            ],
            "buddhism": [
                ["boeddhisme", "Buddhisme"],
                ["boeddha", "Buddha"],
                ["dharma", "dharma"],
                ["nirvana", "nirwana"],
                ["meditatie", "meditasi"],
                ["tempel", "vihara"],
                ["monnik", "biksu"],
                ["non", "biksuni"],
                ["karma", "karma"],
                ["vier edele waarheden", "empat kebenaran mulia"],
                ["achtvoudig pad", "jalan berunsur delapan"],
                ["boeddha-beeld", "patung Buddha"]
            ],
            "confucianism": [
                ["confucianisme", "Konfusianisme"],
                ["Confucius", "Konghucu"],
                ["filosofie", "filsafat"],
                ["harmonie", "harmoni"],
                ["respect", "hormat"],
                ["familie", "keluarga"],
                ["plicht", "kewajiban"],
                ["wijsheid", "kebijaksanaan"],
                ["ritueel", "upacara"],
                ["leraar", "guru"],
                ["moreel", "moral"],
                ["deugd", "kebajikan"]
            ],
            "pc": [
                ["computer", "komputer"],
                ["laptop", "laptop"],
                ["desktop", "komputer meja"],
                ["toetsenbord", "keyboard"],
                ["muis", "mouse"],
                ["scherm", "monitor"],
                ["processor", "prosesor"],
                ["geheugen", "memori / RAM"],
                ["harde schijf", "hard disk"],
                ["besturingssysteem", "sistem operasi"],
                ["internet", "internet"],
                ["software", "perangkat lunak"]
            ],
            "audio": [
                ["geluid", "suara"],
                ["luidspreker", "speaker"],
                ["headset", "headset"],
                ["microfoon", "mikrofon"],
                ["hoofdtelefoon", "headphone"],
                ["versterker", "amplifier"],
                ["subwoofer", "subwoofer"],
                ["soundbar", "soundbar"],
                ["mp3", "mp3"],
                ["streaming", "streaming"],
                ["podcast", "podcast"],
                ["geluidskaart", "sound card"]
            ],
            "video": [
                ["video", "video"],
                ["camera", "kamera"],
                ["film", "film"],
                ["streaming", "streaming"],
                ["YouTube", "YouTube"],
                ["Netflix", "Netflix"],
                ["resolutie", "resolusi"],
                ["4K", "4K"],
                ["HD", "HD"],
                ["editen", "mengedit"],
                ["uploaden", "mengunggah"],
                ["downloaden", "mengunduh"]
            ],
            "zeilen": [
                ["zeilen", "berlayar"],
                ["zeilboot", "perahu layar"],
                ["zeil", "layar"],
                ["mast", "tiang layar"],
                ["schoot", "tali pengikat layar"],
                ["wind", "angin"],
                ["koers", "arah"],
                ["haven", "pelabuhan"],
                ["ankeren", "jangkar"],
                ["kiel", "lunas"],
                ["spinnaker", "spinnaker"],
                ["jacht", "kapal pesiar"]
            ],
            "boot": [
                ["boot", "perahu"],
                ["roeiboot", "perahu dayung"],
                ["speedboot", "perahu cepat"],
                ["motorboot", "perahu bermotor"],
                ["kano", "kano"],
                ["kajak", "kayak"],
                ["roer", "kemudi"],
                ["dek", "dek"],
                ["cabine", "kabin"],
                ["anker", "jangkar"],
                ["reddingsvest", "pelampung penyelamat"],
                ["brandstof", "bahan bakar"]
            ],
            "zee_oceaan": [
                ["zee", "laut"],
                ["oceaan", "samudra"],
                ["strand", "pantai"],
                ["golf", "ombak"],
                ["getijde", "pasang surut"],
                ["stroming", "arus"],
                ["duiken", "menyelam"],
                ["zwemmen", "berenang"],
                ["vissen", "memancing"],
                ["schelp", "kerang"],
                ["zout water", "air asin"],
                ["koraal", "karang"]
            ],
        }
    };